In [1]:
import numpy as np

class Neuron:
    def __init__(self, w, b, f):
        self.w = np.concatenate((w, b), axis=1)
        self.f = f
        
    def output(self, x):
        x = np.concatenate((x, [[1,],]))
        return self.f(self.w.dot(x))

def f(u):
    # numpyの機能
    u[u > 0] = 1    # 0より大きいものを1
    u[u <= 0] = -1
    return u


In [2]:
w = np.array([[0,1],[2,3]])
print(w)

[[0 1]
 [2 3]]


In [3]:
print(w.T)

[[0 2]
 [1 3]]


In [4]:
w = np.array([[1,2,3]])
b = np.array([[10,],])
n = Neuron(w, b, f)
print(w)
print(b)
print(n.w)

[[1 2 3]]
[[10]]
[[ 1  2  3 10]]


In [5]:
x = np.array([[2],[4],[6],])
print(x)
n.output(x)

[[2]
 [4]
 [6]]


array([[1]])

In [6]:
if __name__ == '__main__':
    # １入力１出力
    neuron = Neuron([[1,],], [[0.1,],], f)
    print(neuron.output([[-0.1,],]))
    # ２入力２出力 
    neuron = Neuron([[0.5,0.8,],[-0.1,-0.3]],[[0.1,],[0.1],], f)
    print(neuron.output([[-1,],[0.2,]]))


[[-1.]]
[[-1.]
 [ 1.]]


In [7]:
# W = (1.0, -2.0)
# b = 1.0
# x = ( 0.5 
#      -0.5 )

w = np.array([[1.0, -2.0],])
b = np.array([[1.0,],])
n = Neuron(w, b, f)
x = np.array([[0.5],[-0.5]])
n.output(x)

array([[ 1.]])

In [8]:
bar = np.array([[-2, 1, -3, 4]])
print(bar)
foo = [-1 if v <= 0 else 1 for v in bar[0]]
print(foo)

[[-2  1 -3  4]]
[-1, 1, -1, 1]
